### ISSUE TITLE
Footer missing

### ISSUE THREAD

**Issue by cyrus43** [MillieKinoti/DSC-Web-development-workshop#1]
There is a missing footer in your index.html Dsc website development

**Comment by StanleyMasinde** [comment]
I can see the footer

**Comment by conradKE** [comment]
me to

**Comment by cyrus43** [comment]
My bad, I can see it too

**Comment by stannlee** [comment]
> My bad, I can see it too

@cyrus43 @azim254 maybe we can finish this website

**Comment by cyrus43** [comment]
Maybe if the owner authorizes us to do so.

**Comment by conradKE** [comment]
> > My bad, I can see it too
> 
> @cyrus43 @azim254 maybe we can finish this website

ajaweka license 🤣🤣

**Comment by StanleyMasinde** [comment]
> > > My bad, I can see it too
> > 
> > 
> > @cyrus43 @azim254 maybe we can finish this website
> 
> ajaweka license

By the way, maybe si open-source

**Comment by cyrus43** [comment]
😂😂 Tunataka aseme venye anataka..."face to face guidance

**Comment by StanleyMasinde** [comment]
>  Tunataka aseme venye anataka..."face to face guidance

Sawa master

**Comment by MillicentKinoti** [comment]
don't

**Comment by StanleyMasinde** [comment]
@cyrus43 close this issue already 😂😂😂🏃🏽‍♂️

**Comment by cyrus43** [comment]
Right away 😂😂
