### ISSUE TITLE
Script tag placement

### ISSUE THREAD

**Issue by billthebuilder** [MillieKinoti/DSC-Web-development-workshop#3]
- You've placed your script tags after the `</html>` tag 
- I recommended that you place your script tags before ending the `</body>` tag 
- You can refer to [this](https://stackoverflow.com/questions/436411/where-should-i-put-script-tags-in-html-markup) for more information on this issue

**Comment by StanleyMasinde** [comment]
It is a minor issue though it would be a big problem 😬 in template engines. 
A PR would be nice

**Comment by MillicentKinoti** [comment]
Thanks for that... I'll make changes

**Comment by billthebuilder** [comment]
Just merge the PR I've made changes 😊

**Comment by MillicentKinoti** [comment]
Aight😊

**Comment by StanleyMasinde** [comment]
@BILLthebuilder Time to close the issue I'm seeing pull #4 iko almost merged
